### ISSUE TITLE
entrypoint script permissions

### ISSUE THREAD

**Issue by derhecht** [adamzammit/limesurvey-docker#10]
got 
/usr/local/bin/docker-entrypoint.sh: line 59: application/config/config.php: Permission denied
when running container with another user which is default to Jenkins pipeline Docker commands

may use "sudo" here if available in your Docker base image - or setup directories to be owned by given Docker user

**Comment by adamzammit** [comment]
Hi @derhecht ,

This isn't a use case I am familiar with - so can you please share you Jenkins syntax or a suggested fix and I'll see if I can test/include it.

Adam

**Comment by derhecht** [comment]
Jenkins pipeline is nothing special:

```
docker.image('mariadb:10.5').withRun('-p 3306:3306 --env-file .env.example') { container ->
     def ip = hostIp(container)
     
     /* Wait until mysql service is up */
     docker.image('mariadb:10.5').inside {
       sh "while ! mysqladmin ping -h ${ip} --silent; do sleep 1; done"
     }

     /* check if limesurvey is reachable */
     docker.image('acspri/limesurvey:4.2.7').inside("-p 80:80 --env-file ${workspace}/.env.example --link ${container.id}:mysql -v ${workspace}/upload:/var/www/html/upload") {
        sleep 10
        sh 'curl -f -LI http://localhost/'
     }
   }
```

when starting 3rd docker container, after second is gone, we got the mentioned problem

**Comment by adamzammit** [comment]
Could you please try removing this line in docker-entrypoint.sh:

https://github.com/adamzammit/limesurvey-docker/blob/b044bb416e7679fad05d6a3a4a3d0b59ab58f5ae/docker-entrypoint.sh#L114

and rebuilding and seeing if that fixes it for you?

**Comment by WMBNC** [comment]
Ok will do  will try.. thnx

**Comment by derhecht** [comment]
untested from my side by doesn't make sense this will work. we got a problem in line 59. a change in 114 should not fix that. the Dockerfile in line 37 might be the problem:
https://github.com/adamzammit/limesurvey-docker/blob/b044bb416e7679fad05d6a3a4a3d0b59ab58f5ae/Dockerfile#L37

**Comment by derhecht** [comment]
have a look at https://github.com/docker-library/php/blob/master/7.3/buster/apache/Dockerfile
especially line 65
https://github.com/docker-library/php/blob/b6fd2f70018163227f0f18f3ba1fa4d70e6d929e/7.3/buster/apache/Dockerfile#L65
with -e APACHE_RUN_USER=...
may use this user in your setup steps so also Jenkins could setup this user
and shift chown stuff from Dockerfile to entrypoint incl. this APACHE_RUN_USER

**Comment by derhecht** [comment]
atm this did not the trick :(

**Comment by derhecht** [comment]
in the end problem is more or less described here: https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

**Comment by derhecht** [comment]
ok. i give it up. even the base image php:7.3-apache could not be started with a custom user properly.

i did some small changes:

`ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    userdel -f www-data &&\
    if getent group www-data ; then groupdel www-data; fi &&\
    if getent group ${GROUP_ID} ; then groupdel $(getent group ${GROUP_ID} | cut -d: -f1); fi &&\
    groupadd -g ${GROUP_ID} www-data &&\
    useradd -l -u ${USER_ID} -g www-data www-data &&\
    chown --changes --silent --no-dereference --recursive \
        ${USER_ID}:${GROUP_ID} \
        /var/www/html \
;fi

RUN mkdir -p /var/www/html/plugins && chown -R www-data:www-data /var/www/html/plugins
RUN mkdir -p /var/www/html/upload && chown -R www-data:www-data /var/www/html/upload`

which could be used in Dockerfile may when get those things working...

**Comment by machitgarha** [comment]
I know this is old, but for anyone who faces this problem: The problem is with the permissions of one of three volumes located at `config`, `plugins` or `upload`. You can simply remove them (backup the files if there is any) and the volumes will be recreated by Docker.

**Comment by machitgarha** [comment]
So maybe this issue should be closed.

**Comment by adamzammit** [comment]
Thanks @machitgarha
