### ISSUE TITLE
Question: Is there any limitation on LIMESURVEY_DB_HOST?

### ISSUE THREAD

**Issue by ghost** [adamzammit/limesurvey-docker#11]
Hello

I try to use MySQL on my host but not a container.
And my container bridge IP is 172.23.0.1
So I set LIMESURVEY_DB_HOST to "172.23.0.1:3306"
But I always get MySQL connection error.

Is it possible to use LIMESURVEY_DB_HOST to connect to MySQL on my host?

Thanks!

**Comment by adamzammit** [comment]
Hi @amazonyuribana ,

There is no limitation to LIMESURVEY_DB_HOST. It sounds like mysql is not listening on that interface on your host. Alternatively you could put the container on the host network instead of the bridge network.

Adam

**Comment by ghost** [comment]
> Hi @amazonyuribana ,
> 
> There is no limitation to LIMESURVEY_DB_HOST. It sounds like mysql is not listening on that interface on your host. Alternatively you could put the container on the host network instead of the bridge network.
> 
> Adam

Thanks! 
I figured out that the problem is the firewall which blocking connection to my host.
