### ISSUE TITLE
How to enable HTTPS

### ISSUE THREAD

**Issue by Djent-** [adamzammit/limesurvey-docker#14]
Could you please provide instructions or a configuration to enable HTTPS with provided certificates? Currently, LimeSurvey presents a warning about SSL not being enforced.

As a workaround, I've put my instance behind a reverse proxy to add HTTPS, but links used by the application, such as in the invitation email templates, show as http://... This is not ideal

Thank you

**Comment by adamzammit** [comment]
I also put LimeSurvey behind a reverse proxy. Then I make the following code changes:

in application/extensions/LimeScript/LimeScript.php change:

$data['baseUrl']                    = Yii::app()->getBaseUrl(true);

to

$data['baseUrl']                    = 'https://mylimesurveyurl.com.au';

in  application/config/config.php:

add the config items:

'force_ssl'=>'off', //avoids redirect loops
'publicurl'=>'https://mylimesurveyurl.com.au/',

**Comment by FFricke** [comment]
I got a similar problem. Got a LimeSurvey Instance based on your image with ports 80 and 443 forwarded behind a dyn-DNS service. I'm not able to reach it by https neither via the domain name nor over the ip adress in the local network. Only locally by http.
I even tried out those fixes above even though you wrote, that they are out of datein #37

I would be very glad for some advice

**Comment by adamzammit** [comment]
This LimeSurvey image only runs on port 80. If you want to run on 443/HTTPS - you need to set up a reverse proxy server. You could add this as an additional container in the docker-compose file or run it on the host itself.
