### ISSUE TITLE
DOWNLOAD_URL returns 404

### ISSUE THREAD

**Issue by lukateras** [adamzammit/limesurvey-docker#17]
https://github.com/adamzammit/limesurvey-docker/blob/4af39c7d45a906ba16f1fc97a147bd0a62ec3099/Dockerfile#L3

This URL doesn't seem to exist anymore.

**Comment by adamzammit** [comment]
This build tracks the latest community release. Every time LimeSurvey releases a new version the Dockerfile needs to be updated. I have done this now.
