### ISSUE TITLE
The provided cocker-compose example seems not to work

### ISSUE THREAD

**Issue by maximemoreillon** [adamzammit/limesurvey-docker#19]
Hello,

I tried running the provided docker-compose example as it is but when accessing limesurvey, I get the following screen:

![image](https://user-images.githubusercontent.com/29086128/119424034-9d06f400-bd3f-11eb-8145-4a1b8dea4588.png)

I can't seem to be able to do anything from there. Am I missing something?

**Comment by adamzammit** [comment]
This is the expected behaviour.

Please add: 

/admin

To the URL to view the admin interface

**Comment by maximemoreillon** [comment]
Thanks for the swift answer and please excuse my non-issue!
Got a bit confused by the fact that the admin name and email weren't the ones from the environment variables.
