### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by arjunbazinga** [adamzammit/limesurvey-docker#20]
Hi!

I wanted to run this image to use postgres as the backend instead of mysql.
What would be the necessary changes needed to make that work ? 

I saw crramirez/limesurvey has support for postgres but could not find the equivalent docs.

Thanks.

**Comment by adamzammit** [comment]
Hi,

There would be a few changes required. Firstly the https://github.com/adamzammit/limesurvey-docker/blob/master/Dockerfile would need to be updated to include the PHP postgres modules, then the https://github.com/adamzammit/limesurvey-docker/blob/master/docker-entrypoint.sh would need a new environment variable to determine database type, and also re-implement the database checking and creation code. 

Adam

**Comment by adamzammit** [comment]
This has now been implemented - thank you @bovender for supplying https://github.com/adamzammit/limesurvey-docker/pull/51 . Please check out from version 6.4.8 to test.

**Comment by bovender** [comment]
> Please check out from version 6.4.8 to test.

Works well for me in production! :-)

**Comment by adamzammit** [comment]
Thanks!
