### ISSUE TITLE
kcfinder

### ISSUE THREAD

**Issue by spaquin3** [adamzammit/limesurvey-docker#25]
hello 
just did a fresh install. and trie to upload picture in buy setting/ressources tab but when i clic on upload nothing all button upload, refresh, setting do nothing. not sur if the problem is me. put a screenshot of thge debug console in firefox 
![Sans titre](https://user-images.githubusercontent.com/47509313/137598369-d348dbcb-bf94-46c9-9fb3-265eeec90e76.png)
.

**Comment by adamzammit** [comment]
Uploading an image works for me in settings/resources

Please confirm what version of this docker image you are using, and what parameters you passed to start the image.

Also please try on another browser / without any plugins enabled.
