### ISSUE TITLE
KCFinder for uploading images not working

### ISSUE THREAD

**Issue by Stokel** [adamzammit/limesurvey-docker#27]
The docker-compose seems to be working fine except that somehow the KCfinder to upload images is not working.

In Firefox 96.0.2 (64-bit) the KCfinder window opens but all the buttons do not respond.
Using Chrome 97.0.4692.99 the browser wants to use linux xdg-open when clicking on any button in the KCfinder.

I am not sure if this is a problem with this docker(-compose) instance or a problem with limesurvey itself.

**Comment by adamzammit** [comment]
Thanks for this report - but I can't replicate it here on the "master" branch 

Are you running this locally or is it behind a reverse proxy?

**Comment by Stokel** [comment]
At the moment it is running and accessed locally only as we are still evaluating if we want to use it.

**Comment by adamzammit** [comment]
Have a look at the debug console in firefox/chrome - it may be a local browser plugin blocking this

**Comment by Stokel** [comment]
Found time to look into it a bit more.
To be more precise: We had the container running in a vm on a remote host without setting up HTTPS or a domain name, as this was only for evaluating whether we wanted to use limesurvey. In this setup the KCFinder does not work.
When setting up the container with the same configuration locally on two other devices and only connecting locally, the KCFinder does work on both machines. Connecting to those machines remotely will again make the KCFinder non functioning for the remotely connecting user.

So I guess we have to setup proper HTTPS after all?
Or are there other factors at play here?

**Comment by adamzammit** [comment]
I don't think it is related to HTTPS - I think it is related to the cookie domain that LimeSurvey sets for KCFinder.

See here to set it manually which would make it work over the vm + Docker:  

https://manual.limesurvey.org/Optional_settings#Request_settings

These bugs for reference:

https://bugs.limesurvey.org/view.php?id=9118
https://bugs.limesurvey.org/view.php?id=11618

**Comment by Stokel** [comment]
Sorry for the late update. After setting up the container with traefik and let's encrypt everything is working now.
Thank you for you again.
