### ISSUE TITLE
Unbound variable error

### ISSUE THREAD

**Issue by Stokel** [adamzammit/limesurvey-docker#29]
After updating the container (latest tag) I get the following error:
```
/usr/local/bin/docker-entrypoint.sh: line 118: LIMESURVEY_USE_DB_SESSIONS: unbound variable
```

It seems this variable was recently added to the docker-entrypoint.sh.

Have I forgotten to configure something?
It worked before updating.

**Comment by adamzammit** [comment]
Thanks for this note - please try the latest edition: https://github.com/adamzammit/limesurvey-docker/releases/tag/5.2.14.1

**Comment by Stokel** [comment]
Thank you very much for the swift fix.
Seems to be working again with the "latest" tag.
