### ISSUE TITLE
Mysql errors after upgrading containers

### ISSUE THREAD

**Issue by Stokel** [adamzammit/limesurvey-docker#31]
Is there a known error in one of the latest upgrades or upgrade processes?
I had a limesurvey:latest instance running for about 4 weeks, without upgrading because I didn't want to risk a downtime.

Now after the time for the survey has ended I wanted to upgrade due to a "security issue" warning.

After pulling and starting the newest versions of my services the mariadb service is throwing these to errors without end:
```
mysql_1       | 2022-07-02  7:31:26 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
mysql_1       | 2022-07-02  7:31:26 14 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
```
I can access LimeSurvey and it tells me that "The database has been updated from version 486 to version 488."
Everything seems to be working, but the errors in the log do worry me.

I haven't changed my configuration, which was working before without problems.
I'm using the docker-compose example with added traefik.

**Comment by adamzammit** [comment]
Hi @Stokel .

This looks more like an issue with Mariadb updating but not upgrading correctly. Can you please check for any mariadb issues?

Also in future it might be best to peg mariadb to a known working version. I'm going to update the default docker compose files to do that now (10.5 is known to work well)

Adam

**Comment by adamzammit** [comment]
I made that change here: https://github.com/adamzammit/limesurvey-docker/commit/e5787128423c71c3bd28deac2d7acf919e5a19fe let me know if this reoccurs and we can reopen this issue
