### ISSUE TITLE
Set timezone

### ISSUE THREAD

**Issue by o-pteron** [adamzammit/limesurvey-docker#34]
Is there (or could you make) a way to set the server timezone in docker-compose.yml?

As far as I can se the timezone is hard coded in Dockerfile:55
`echo 'date.timezone=UTC'; \`
But I'm not a developer myself.

A possible fix is to set "Time difference" (Global settings -> General) but daylight savings makes this a repeating manual task.

Thank you for your work and for maintaining this repository.

**Comment by adamzammit** [comment]
Thanks - this is a good suggestion - I'll work on this . I should have something to test in a week or so

**Comment by adamzammit** [comment]
This is now available in the latest releases on both Master and LTS - please let me know if it doesn't work for you.

**Comment by o-pteron** [comment]
It works flawlessly, thanks!
