### ISSUE TITLE
Feature: Persistent sessions accross container restarts

### ISSUE THREAD

**Issue by amenk** [adamzammit/limesurvey-docker#35]
I think we should persist sessions across container restarts, otherwise users who are in the middle of a survey for example during server restarts or upgrade will use their progress.

Should be possible with 
* setting a specific session_save_path in php.ini
* mounting that path in docker composer

**Comment by amenk** [comment]
will make a PR

**Comment by adamzammit** [comment]
thanks again - I've merged this and will be available in the 5.6.11 release
