### ISSUE TITLE
SMTP mail from not set correctly

### ISSUE THREAD

**Issue by clement-deltel** [adamzammit/limesurvey-docker#48]
Hello,

I am trying to configure SMTP capabilities for Limesurvey with this Docker image. However, I am facing some issues when it comes to testing my configuration. 

I set all the following environment variables:

LIMESURVEY_SMTP_HOST=${SMTP_HOST}:${SMTP_PORT}
LIMESURVEY_SMTP_USER=${SMTP_USERNAME}
LIMESURVEY_SMTP_PASSWORD=${SMTP_PASSWORD}
LIMESURVEY_SMTP_SSL=tls

In the LimeSurvey UI, I set the "Default site admin email" to be something that matches the domain of my SMTP server. But When I hit the "Send test email", I get the following error:

SERVER -> CLIENT: 554 Message rejected: Email address is not verified. The following identities failed the check: your-email@example.net

And in the logs of the send email test, I am also picking up those two lines:

CLIENT -> SERVER: MAIL FROM:<your-email@example.net>
CLIENT -> SERVER: From: AdminName <noreply-survey@domain.com>

Even with my configuration changes, it seems that it is picking up the default configuration for the MAIL FROM address, and not the one that I set. I looked into the configuration files, it appears in email.php but those are only default values, the actual values are in config.php and match what I set. Then, I don't understand where the "your-email@example.net" is picked up from...

Would that be possible to add a LIMESURVEY_SMTP_FROM environment variable to set that properly? Thanks for considering my request.

**Comment by adamzammit** [comment]
Thanks @clement-deltel 

The LimeSurvey config variable for this is: siteadminbounce

I've updated the code to handle this now with the new env var: LIMESURVEY_FROM_EMAIL

But please note for an existing config file - you will need to first manually add the key: siteadminbounce

**Comment by clement-deltel** [comment]
Thank you very much for handling this issue so quickly!
