### ISSUE TITLE
Permission Denied when restarting the server

### ISSUE THREAD

**Issue by DerAndereJohannes** [adamzammit/limesurvey-docker#49]
Hi, I just found your project and am excited to see it.
I tried to use the default docker-compose file that is provided in the repository to create the server. For the first creation and boot up, everything seems to work fine. All the files are created and the server works great. However, if I power down the containers and start them up again at a future time, I get the following error: 
```
limesurvey-1  | Copying default container default config files into config volume...
limesurvey-1  | cp: cannot create regular file 'application/config/config-defaults.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/config-sample-dblib.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/config-sample-mysql.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/config-sample-pgsql.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/config-sample-sqlsrv.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/console.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/email.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/fonts.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/index.html': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/internal.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/ldap.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/packages.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/questiontypes.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/rest/v1/example/survey-patch-all.json': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/rest/v1/session.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/rest/v1/survey.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/rest/v1.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/rest.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/routes.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/tcpdf.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/updater_version.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/vendor.php': Permission denied
limesurvey-1  | cp: cannot create regular file 'application/config/version.php': Permission denied
```

If I delete the config folder that the initial initialization did, then the server works again. However, removing the config on every reboot does seem excessive. The only related issue I found was at the end of #10 , however there the solution was to delete the config folder.

other info:
- Windows 10 machine (fully up to date)
- WSL 2 enabled
- Docker version 24.0.7
- Tried on Limesurvey versions 6.3.8 and 6.3.9

Thanks in advance.

**Comment by adamzammit** [comment]
I can't replicate this on a linux host, but the permissions in the Docker image weren't perfect, so I've created a test image on docker hub with updated permissions - 

adamzammit/limesurvey:6.3.9.1

can you please update the docker-compose file with that image name and try again. If that fixes the issue I know what is going on.

**Comment by DerAndereJohannes** [comment]
Hi Adam, thanks for the speedy response.

I just tried the new version you mentioned in your comment and I am still receiving the same error. Could it be that it is somehow to even recognizing that the folder exists? 

`limesurvey-1  | Copying default container default config files into config volume...`

This line in the log is especially curious as it would indicate that doesn't exist and then tries to overwrite the files that are already there which leads to the error.

Let me know if there is anything else I can do.

**Comment by adamzammit** [comment]
thanks - yes it does need to overwrite the files as if the files on the container are updated (i.e version update) then it must make sure the local files are updated too.

I've added a force parameter to the copy function and rebuilt the image - please try this one:

adamzammit/limesurvey:6.3.9.2

Adam

**Comment by adamzammit** [comment]
If that doesn't work it is probably something to do with the way permissions work on a Windows host. 

What is happening in effect is that the user in the container is copying files from the container to a volume. If that volume is mapped on the host and the permissions are restrictive, it will fail.

In that case it might be better not to volume mount the config directory and just leave it as a regular volume (i.e remove the volume mount line from the docker-compose file and it should work)

**Comment by DerAndereJohannes** [comment]
Thank you very much for your detailed responses and updates, I appreciate it a lot.

The new version (6.3.9.2) has fixed the issue on my windows host! I think your explanations are all correct.

For the sake of completeness, I also tested 6.3.9 after deleting the config line in the docker compose yaml file. It worked out exactly as you have mentioned. Ill keep this final tip in mind for the next I come across this issue.

Have a good one
- Johannes

**Comment by adamzammit** [comment]
thanks for testing.

The fix will appear in the next release.

**Comment by fturmel** [comment]
@adamzammit Thanks for the great project! Any chance the fix could be applied to the v5 branch too? I'm getting the same errors on a macOS host with Docker Desktop and not ready to move this client to v6.
