### ISSUE TITLE
Unable to copy survey

### ISSUE THREAD

**Issue by Hooteo** [adamzammit/limesurvey-docker#52]
Hi i have a problem when i try to copy a survey.
Procedure:
1) Create New Survey
2) Copy
3) Select survey that i want to copy , set new name

For all of them i have this message error:

500: Internal Server Error XMLWriter::startElement(): Argument #2 must be a valid element name, "@attributes" given

Server Ubuntu 22.04
Docker latest version

![image](https://github.com/adamzammit/limesurvey-docker/assets/17424781/69cfd952-b6c9-4e6a-b44c-87985dd01f2d)

**Comment by adamzammit** [comment]
Hi @Hooteo  apologies for the delay in responding. 

Can you please confirm if this still occurs on the latest build? 

If it does - it looks like an upstream issue that could be related to what template you are using - do you know what template this is?

Adam

**Comment by Hooteo** [comment]
> Hi @Hooteo apologies for the delay in responding.
> 
> Can you please confirm if this still occurs on the latest build?
> 
> If it does - it looks like an upstream issue that could be related to what template you are using - do you know what template this is?
> 
> Adam

Hi Adam,

it's already been updated from latest docker image.
I still face the issue. All the templates are Bootswatch (modified by me to have different colors and terms and conditions):
![image](https://github.com/adamzammit/limesurvey-docker/assets/17424781/26ce0171-7d37-41df-86e4-8f8b9c29cb6c)
If i use the default bootswatch and not the personalized one i still can't copy the survey

Leonardo

**Comment by adamzammit** [comment]
Can you please try changing the theme on an existing survey to a non bootswatch related theme and then trying again. If it works - it could be related to this bug: https://bugs.limesurvey.org/view.php?id=19049

**Comment by Hooteo** [comment]
Unfortunately, you are right. With fruity it works. The problem with fruity is that I have to modify the template too much to make it decent and presentable to customers. Do you think this will be solved in the future?

**Comment by Hooteo** [comment]
OK I remember that bug you opened. I think it was as a result of the same report I made last year.
Previously we had a dedicated limesurvey server but as you know it is much easier to upgrade and migrate a docker than a db and application installed ad-hoc on a server. I hope it will be fixed soon because many surveys we copy from year to year and it would be quite inconvenient to have to change the theme and then switch to custom bootswatch.

**Comment by Hooteo** [comment]
I completely redesigned our theme based on fruity. I have now applied it to all the surveys I have done in the past and the copy actually works.

**Comment by adamzammit** [comment]
Good workaround!

I ran a test from a new install extending bootswatch theme and then copying that survey. There was no error. My guess is that the fix the LS team applied wasn't retrospective and there may be something in your DB that brings up this error.
