### ISSUE TITLE
Reverse proxy limesurvey to sub-path

### ISSUE THREAD

**Issue by C0NZZ** [adamzammit/limesurvey-docker#54]
I would like the limesurvey image to run on a sub-path of my domain. The base of limesurvey should be domain.com/survey.

Apache Reverse Proxy Config:
```
ProxyPass /survey http://127.0.0.1:9355/
ProxyPassReverse /survey http://127.0.0.1:9355/
```
However, limesurvey always redirects sub-paths to domain.com, causing issues with, like, everything (of course).
(Example: instead of loading files from domain.com/survey/tmp/, it tries to load from domain.com/tmp/. When I open domain.com/survey/admin, it redirects to domain.com/admin)

I saw your [comment in #14](https://github.com/adamzammit/limesurvey-docker/issues/14#issuecomment-689851318) and tried what you described there (kind of a last resort), but it didn't seem to work.

Can you guide me towards a working solution for my problem? Thanks a lot.

**Comment by adamzammit** [comment]
this is a tricky one as LimeSurvey writes a lot of paths in html as relative paths which would need to be rewritten.

There isn't really a good solution for this.

You could try editing the LS application/config.php file and adding in this (within the 'components' array, around line 45):

```
    'request' => array (                                                    
        'baseUrl' => '/survey',                                             
        'hostInfo' => 'http://localhost:9355/survey',
        'scriptUrl' => 'index.php',                                             
   ),   

```

but I don't think it will rewrite all URLs

Adam

**Comment by C0NZZ** [comment]
Okay, thanks. When I used limesurvey without docker, it ran on a sub-path exactly like I described, so I didn't think that this would be too tricky. I will just resort to running it on a subdomain.
Thanks again for your quick response and for maintaining this project!
