### ISSUE TITLE
index.php showing up in URLs

### ISSUE THREAD

**Issue by Lx** [adamzammit/limesurvey-docker#58]
Hi Adam,

Thank you for your ongoing efforts to offer up-to-date versions of LimeSurvey as a Docker container.

I've noticed that a lot of URLs are showing up with a superfluous `index.php/` in them:

- `https://limesurvey.mydomain/index.php/772916`
- `https://limesurvey.mydomain/index.php/admin/index`
- etc.

Interestingly, the URLs all work even when the `index.php/` component is removed, so the issue seems to be more to do with URL generation.  Looking at the source of generated pages, they do indeed contain `index.php/` in all their outgoing links.

In your view, is this likely to be a direct LimeSurvey limitation or potentially something that can be dealt with via the Dockerfile somehow?  I know that these things can sometimes be tweaked with environment variables or the like—I'm yet to delve too deeply into [the Configuration section of the manual](https://manual.limesurvey.org/Administering_LimeSurvey/en).

—Alex

**Comment by ryanb3n** [comment]
I have the same issue.
The .htaccess include a rewrite rule to remove index.php from url's. However the index.php shows in all links. I use the latest version: 6.5.16+240708 , PHP 8.3

I also have ver 4 on another machine with PHP 8.1 where the issue doesn't exist. I tried to compare the .htaccess of both and haven't noticed any major difference.

Any idea how to remove index.php from the url's?

**Comment by ryanb3n** [comment]
Check this answer I got on another site:
https://forums.limesurvey.org/forum/installation-a-update-issues/156174-remove-index-php-from-url-s#265882

**Comment by adamzammit** [comment]
Hi @Lx ,

Thanks! 

Please set this env var and you can hide the index.php file:

https://github.com/adamzammit/limesurvey-docker/blob/3e3a1d940403e88f1146d0a10d09762a0ea01047/README.md?plain=1#L69

Adam

**Comment by Lx** [comment]
Thanks Adam, and sorry—I’m frustrated that I somehow missed that setting in the README earlier.  Working perfectly.
