### ISSUE TITLE
image failing on download of Baltimore cert

### ISSUE THREAD

**Issue by adamzammit** [adamzammit/limesurvey-docker#7]
From: https://github.com/adamzammit/limesurvey-docker/pull/6#issuecomment-627031251

@EtienneBourque thanks I have enabled issues now.

I did some testing and this issue is occurring it appears to be with the download url - I will update this shortly and re-issue the builds.

**Comment by EtienneBourque** [comment]
Works like a charm! Thanks, it was super fast!

**Comment by JamesCullum** [comment]
Still encountering this issue - log only shows this part when using "latest".

Can confirm that it is confirmed in LTS/3, but the latest/4 is still having this issue.
EDIT: Tested 4.2.4 specificially and there it works - maybe a caching issue.

**Comment by adamzammit** [comment]
Hi @JamesCullum . Thanks for the updates. I tested again on 4.2.5 and it all seems fixed now.
