### ISSUE TITLE
MySQL server certificates are not verified when passing MYSQL_SSL_CA

### ISSUE THREAD

**Issue by varseand** [adamzammit/limesurvey-docker#8]
Hello

I was performing small code review before running the container and I've noticed that when MYSQL_SSL_CA environment variable is passed on runtime, the docker-entrypoint.sh sets these PDO attributes:
```
if [ -n "$MYSQL_SSL_CA" ]; then
    set_config 'attributes' "array(PDO::MYSQL_ATTR_SSL_CA => '\/var\/www\/html\/$MYSQL_SSL_CA', PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false)"
fi
```

It misses the point a bit from security perspective as MySQL CA validation was created with intention to validate if the certificate of a server we are connecting was issued by certain CA - to prevent man-in-the-middle attacks. On the other hand, the script sets PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT to false what instructs PDO to skip cryptographic checks at all, making PDO::MYSQL_ATTR_SSL_CA effectively ignored.

I don't know the original intention but my suggestion would be to remove PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT from attributes or set it explicitly to true.

**Comment by adamzammit** [comment]
Hi @kkatowiczk ,
Thanks for pointing this out. You are correct that this is set to false. The reasoning is that this feature (MYSQL_SSL_CA) was added to allow this image to work on Azure and connect to the Azure Database for MySQL/MariaDB.

This only works when MYSQL_ATTR_SSL_VERIFY_SERVER_CERT  is set to false. See here: https://docs.microsoft.com/en-us/azure/mysql/concepts-compatibility

I will update the documentation to reflect the reasoning behind it is clear.

Adam
