### ISSUE TITLE
docker-entrypoint.sh does not check folder first

### ISSUE THREAD

**Issue by derhecht** [adamzammit/limesurvey-docker#9]
we running images inside Jenkins which setup e.g. working dir for Docker images on default (with -w) to Jenkins job workspace folder

your LimeSurvey is extracted to /var/www/html

the docker-entrypoint.sh script does not check working dir and just checks if application config exists in current folder and even try to copy it from there

could you take care of different working dir by e.g. just switch dir on docker-entrypoint.sh or use full path?

**Comment by adamzammit** [comment]
Thanks @derhecht 
I've updated the entrypoint file - let me know if you still have issues after this update.
Adam

**Comment by derhecht** [comment]
sry, open next issue because of permission issue now
